ALTER TABLE users ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE reviews ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE groups ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE group_members ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE group_contents ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE favorites ALTER COLUMN created_at DROP DEFAULT;
